[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Recommended: Set the baud rate for the Serial Monitor
monitor_speed = 115200

; Optional: Increase upload speed to save time (standard is 115200)
upload_speed = 921600
upload_port = COM5